
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    #ports:
    #  - "3306:3306"

  proxy:
    image: proxysql/proxysql
    configs:
      - source: proxy
        target: /etc/proxysql.cnf
    volumes:
      - proxysql:/var/lib/proxysql
    ports:
      - "3306:6033"

volumes:
  proxysql:

configs:
  proxy:
    content: |
      datadir="/var/lib/proxysql"
      
      mysql_servers=
      {
        {
          hostgroup_id=1
          hostname="db"
          port=3306
        }
      }

      admin_variables=
      {
           # TODO: Remove admin access as we will expose it as host network
           admin_credentials="admin:admin;"
           mysql_ifaces="0.0.0.0:6032"
      }
      
      mysql_user=
      {
        username="${DB_USER}"
        password="${DB_PASSWORD}"
        default_hostgroup=1
      }

      mysql_variables=
      {
#           threads=4
#           max_connections=2048
#           default_query_delay=0
#           default_query_timeout=36000000
#           have_compress=true
#           poll_timeout=2000
           interfaces="0.0.0.0:6033"
#           default_schema="information_schema"
#           stacksize=1048576
#           server_version="5.5.30"
#           connect_timeout_server=3000
#           monitor_username="monitor"
#           monitor_password="monitor"
#           monitor_history=600000
#           monitor_connect_interval=60000
#           monitor_ping_interval=10000
#           monitor_read_only_interval=1500
#           monitor_read_only_timeout=500
#           ping_interval_server_msec=120000
#           ping_timeout_server=500
#           commands_stats=true
#           sessions_sort=true
#           connect_retries_on_failure=10
      }